apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260525-135220-3tmlel8kxhrj-service
spec:
  selector:
    app: enterprise-system-20260525-135220-3tmlel8kxhrj
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
